2025-01-31 22:50:27,438:DEBUG:certbot._internal.main:certbot version: 3.1.0
2025-01-31 22:50:27,439:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2025-01-31 22:50:27,439:DEBUG:certbot._internal.main:Arguments: ['--standalone', '--email', 'karimmaroous@gmail.com', '--agree-tos', '--no-eff-email', '--staging', '-d', 'opsforall.net']
2025-01-31 22:50:27,439:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2025-01-31 22:50:27,455:DEBUG:certbot._internal.log:Root logging level set at 30
2025-01-31 22:50:27,455:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2025-01-31 22:50:27,456:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x75f95af992b0>
Prep: True
2025-01-31 22:50:27,456:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x75f95af992b0> and installer None
2025-01-31 22:50:27,456:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2025-01-31 22:50:27,535:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/182784314', new_authzr_uri=None, terms_of_service=None), 5c0ea7419c19db18f607881e60bb62df, Meta(creation_dt=datetime.datetime(2025, 1, 31, 21, 18, 24, tzinfo=datetime.timezone.utc), creation_host='f5a16ff59e49', register_to_eff=None))>
2025-01-31 22:50:27,536:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2025-01-31 22:50:27,539:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org:443
2025-01-31 22:50:27,718:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 974
2025-01-31 22:50:27,720:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 31 Jan 2025 22:50:27 GMT
Content-Type: application/json
Content-Length: 974
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "WDya31bchaQ": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "profiles": {
      "classic": "The same profile you're accustomed to",
      "tlsserver": "https://letsencrypt.org/2025/01/09/acme-profiles/"
    },
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-staging-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2025-01-31 22:50:27,724:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for opsforall.net
2025-01-31 22:50:27,726:DEBUG:acme.client:Requesting fresh nonce
2025-01-31 22:50:27,728:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce.
2025-01-31 22:50:27,787:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2025-01-31 22:50:27,788:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 31 Jan 2025 22:50:27 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: N9Ep_yiTJyJIjLcDv3NU2wxgC_uKrjX17zRjEf0ZPA6OoFDXiYg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2025-01-31 22:50:27,789:DEBUG:acme.client:Storing nonce: N9Ep_yiTJyJIjLcDv3NU2wxgC_uKrjX17zRjEf0ZPA6OoFDXiYg
2025-01-31 22:50:27,790:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "opsforall.net"\n    }\n  ]\n}'
2025-01-31 22:50:27,796:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xODI3ODQzMTQiLCAibm9uY2UiOiAiTjlFcF95aVRKeUpJakxjRHYzTlUyd3hnQ191S3JqWDE3elJqRWYwWlBBNk9vRkRYaVlnIiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "rFiXcD-VPGMvA9soEAmjQnoiGvr4huK2U-dTkxQW3HN2hqydaSjthmg4Ze8bY35GbGj065_q33OykjN77ff_e7RDgZDCc-53NaHkOjpFpT1ewPOKXfHtBrK6DYzmn6g5z_GVlf9bbYeUA7tbvW79EwLBqAD7FAjq958dO_3PIYgVCZNF0T8gDA9Df4ZhFezMJ6PGWEyR350MUo_fFomrB2d6e9r9Hba8ihICktUY9QDPyV50TAbxkgV9stUUxOY6psExQSPevd9EMGRVlWOYc3plq6IMxQdHVahr78rGAktVt8zn8uZwVMfpvYHaJAwlLR3BE2ELO1j7T-_Ce1P-MA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm9wc2ZvcmFsbC5uZXQiCiAgICB9CiAgXQp9"
}
2025-01-31 22:50:27,887:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 359
2025-01-31 22:50:27,889:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 31 Jan 2025 22:50:27 GMT
Content-Type: application/json
Content-Length: 359
Connection: keep-alive
Boulder-Requester: 182784314
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/182784314/22334403754
Replay-Nonce: xMYr_xatC5ZE9z8Z9vnotkY470CT13m08WJw7irQEBtttwcHuRQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-02-07T22:50:27Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "opsforall.net"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz/182784314/15902831624"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/182784314/22334403754"
}
2025-01-31 22:50:27,889:DEBUG:acme.client:Storing nonce: xMYr_xatC5ZE9z8Z9vnotkY470CT13m08WJw7irQEBtttwcHuRQ
2025-01-31 22:50:27,890:DEBUG:acme.client:JWS payload:
b''
2025-01-31 22:50:27,893:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz/182784314/15902831624:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xODI3ODQzMTQiLCAibm9uY2UiOiAieE1Zcl94YXRDNVpFOXo4Wjl2bm90a1k0NzBDVDEzbTA4V0p3N2lyUUVCdHR0d2NIdVJRIiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzE4Mjc4NDMxNC8xNTkwMjgzMTYyNCJ9",
  "signature": "hXpFpVmUqtxCLdACjKn4V6MRVQpfZ9b3S3DOr6_jcNTNf4lsVjp3DCHMcYvMfHGV85MsjlaXzr-dvXPyi5JwU0nNZSKgTMF_R_MbsXei27nrGy3_5h3QTLwVePdY6yONgzoRlTvX8nTnA5-lxnPcaUMTBXifkg7nJck8r32tH_e4NfcKzyfKyWK6YBTLxknJvHKLiKnBUdaSKflGGdkjDJXtmROeFRRaTppoacIyeqIZKqmgC4vNF25IjGA68J_GOpbUJcZxMy0kYT716NRBs8OcUDo0viM3MBpffjt1JHDoInIk1Mp8s0Vc2NWXqByE3lPrmBpO3-BME8PL1ZTBkA",
  "payload": ""
}
2025-01-31 22:50:27,959:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz/182784314/15902831624 HTTP/1.1" 200 839
2025-01-31 22:50:27,963:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 31 Jan 2025 22:50:27 GMT
Content-Type: application/json
Content-Length: 839
Connection: keep-alive
Boulder-Requester: 182784314
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xMYr_xatQ0ryQMWsQTTT64wIEG9MUNaFCUqBzothi2KfAWZXQSs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "opsforall.net"
  },
  "status": "pending",
  "expires": "2025-02-07T22:50:27Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/k1WsUA",
      "status": "pending",
      "token": "luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA"
    },
    {
      "type": "dns-01",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/yZowNw",
      "status": "pending",
      "token": "luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA"
    },
    {
      "type": "http-01",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/NufiqQ",
      "status": "pending",
      "token": "luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA"
    }
  ]
}
2025-01-31 22:50:27,963:DEBUG:acme.client:Storing nonce: xMYr_xatQ0ryQMWsQTTT64wIEG9MUNaFCUqBzothi2KfAWZXQSs
2025-01-31 22:50:27,964:INFO:certbot._internal.auth_handler:Performing the following challenges:
2025-01-31 22:50:27,964:INFO:certbot._internal.auth_handler:http-01 challenge for opsforall.net
2025-01-31 22:50:27,964:DEBUG:acme.standalone:Successfully bound to :80 using IPv6
2025-01-31 22:50:27,964:DEBUG:acme.standalone:Certbot wasn't able to bind to :80 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
2025-01-31 22:50:27,969:DEBUG:acme.client:JWS payload:
b'{}'
2025-01-31 22:50:27,980:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/NufiqQ:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xODI3ODQzMTQiLCAibm9uY2UiOiAieE1Zcl94YXRRMHJ5UU1Xc1FUVFQ2NHdJRUc5TVVOYUZDVXFCem90aGkyS2ZBV1pYUVNzIiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzE4Mjc4NDMxNC8xNTkwMjgzMTYyNC9OdWZpcVEifQ",
  "signature": "d9H_cBn9bGi0ON4LIWAOg5m3nKke2plyDFOGgDUSxML8BsydVRRinCJicTPi4QfMW2C9kdYB6idZ-YQkd7hRGv1LqR_PQAzwH8EQJfSwi_4dMKbxpnUcPXqQnR6uQHEHr8vA3Mo_1DAfq34aQDkyPtTkOvdT_yd4BzSuxDK63yw-yXFanmMY1CW6_1ZyB3bhmY9Sj5IoZa-Gm9ZvYjVwiU2YlcDao8Ewx6jMp2Fcpgko5JvMSzqPT0mcX_bPZZwcLvdpXjt_Yg-yYM9-EPhonLe1daR7UC1Za5wtEXCMQw7q1OhoH4MSzEYsoY0uzwvQvoSY6JJCqTqv9DLCrSukbA",
  "payload": "e30"
}
2025-01-31 22:50:28,055:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/chall/182784314/15902831624/NufiqQ HTTP/1.1" 200 201
2025-01-31 22:50:28,056:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 31 Jan 2025 22:50:28 GMT
Content-Type: application/json
Content-Length: 201
Connection: keep-alive
Boulder-Requester: 182784314
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-staging-v02.api.letsencrypt.org/acme/authz/182784314/15902831624>;rel="up"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/NufiqQ
Replay-Nonce: N9Ep_yiTZE3czmoKVDZfwCoA-k6rVr7Ip9YL8RuNoNQlPtbwqso
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/NufiqQ",
  "status": "pending",
  "token": "luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA"
}
2025-01-31 22:50:28,058:DEBUG:acme.client:Storing nonce: N9Ep_yiTZE3czmoKVDZfwCoA-k6rVr7Ip9YL8RuNoNQlPtbwqso
2025-01-31 22:50:28,058:INFO:certbot._internal.auth_handler:Waiting for verification...
2025-01-31 22:50:29,058:DEBUG:acme.client:JWS payload:
b''
2025-01-31 22:50:29,060:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/authz/182784314/15902831624:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xODI3ODQzMTQiLCAibm9uY2UiOiAiTjlFcF95aVRaRTNjem1vS1ZEWmZ3Q29BLWs2clZyN0lwOVlMOFJ1Tm9OUWxQdGJ3cXNvIiwgInVybCI6ICJodHRwczovL2FjbWUtc3RhZ2luZy12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzE4Mjc4NDMxNC8xNTkwMjgzMTYyNCJ9",
  "signature": "L7VAfzDapz9vKgZEOCA120rtE0BvsXhtLldB3mrgAsKyV2oLxQ61v6rVdpDwUNB62uJoFmbtvRoiFD2p7S4wadUhTAd7eDZndYmjAFw1KWn0ecVFdMmRisneCTvevbn7dsHBMZNKqh82Xf465f5en5c6O6HTJ8XL0Wbq51fbl0WwqaxcpES597UdX_41ual92_xKL0cceEE1Nv3DOwzdYI4aK6aPQPfL6tYC1I3XDNFcusLxuyBqshsPbb0zANEn7XvCAoG1NMjf6JD4cM4OTFhBcJcO7KurqEmNIoatI9TYRPNQyg2nZhM9BobfKt60jKvN9vTxmFjO3sbLqHRgOA",
  "payload": ""
}
2025-01-31 22:50:29,124:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/authz/182784314/15902831624 HTTP/1.1" 200 1031
2025-01-31 22:50:29,124:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 31 Jan 2025 22:50:29 GMT
Content-Type: application/json
Content-Length: 1031
Connection: keep-alive
Boulder-Requester: 182784314
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xMYr_xat9jT8C8DHAjCRSgSdlJ_FiV2DSQOaOKTAJfHLPCneQ6I
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "opsforall.net"
  },
  "status": "invalid",
  "expires": "2025-02-07T22:50:27Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall/182784314/15902831624/NufiqQ",
      "status": "invalid",
      "validated": "2025-01-31T22:50:28Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "54.226.228.6: Invalid response from http://opsforall.net/.well-known/acme-challenge/luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA: 404",
        "status": 403
      },
      "token": "luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA",
      "validationRecord": [
        {
          "url": "http://opsforall.net/.well-known/acme-challenge/luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA",
          "hostname": "opsforall.net",
          "port": "80",
          "addressesResolved": [
            "54.226.228.6"
          ],
          "addressUsed": "54.226.228.6"
        }
      ]
    }
  ]
}
2025-01-31 22:50:29,124:DEBUG:acme.client:Storing nonce: xMYr_xat9jT8C8DHAjCRSgSdlJ_FiV2DSQOaOKTAJfHLPCneQ6I
2025-01-31 22:50:29,125:INFO:certbot._internal.auth_handler:Challenge failed for domain opsforall.net
2025-01-31 22:50:29,125:INFO:certbot._internal.auth_handler:http-01 challenge for opsforall.net
2025-01-31 22:50:29,125:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: opsforall.net
  Type:   unauthorized
  Detail: 54.226.228.6: Invalid response from http://opsforall.net/.well-known/acme-challenge/luplXH2aUxh0UqWX_I9Fa3ygwKP04zcxrIj6WP4VSoA: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

2025-01-31 22:50:29,126:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2025-01-31 22:50:29,126:DEBUG:certbot._internal.error_handler:Calling registered functions
2025-01-31 22:50:29,126:INFO:certbot._internal.auth_handler:Cleaning up challenges
2025-01-31 22:50:29,127:DEBUG:certbot._internal.plugins.standalone:Stopping server at :::80...
2025-01-31 22:50:29,471:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1873, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1579, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 518, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 429, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 497, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2025-01-31 22:50:29,473:ERROR:certbot._internal.log:Some challenges have failed.
